# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "94fc001a499320252eb75f93ee5652cd"
name = "zhafran-app"
application_url = "https://zhafran-beta.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_files"

[auth]
redirect_urls = [
  "https://zhafran-beta.vercel.app/auth/callback",
  "https://zhafran-beta.vercel.app/auth/shopify/callback",
  "https://zhafran-beta.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2026-10"
